---

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ticketsale_db?serverTimezone=UTC&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate: org.hibernate.dialect.MySQL5InnoDBDialect

...